config/routes.rb
Rubyrage::Application.routes.draw do
 root :to => 'welcome#index'

 # resources :users
 get '/users/new' => 'users#new', as: "new_user"
 post '/users' => 'users#create'

 get "log_out" => "sessions#destroy", as: "log_out"
 get '/sessions/recentsessions' => 'sessions#recentsessions'
 resources :sessions

 get '/games/dashboard' => 'games#dashboard'
 get '/games/single' => 'games#single'
 post '/games/gamebroadcast' => 'games#gamebroadcast'
 post '/games/multi/triggerBattleGame' => 'games#triggerBattleGame', as: "triggerBattleGame"
 post '/games/multi/requestBattle' => 'games#requestBattle', as: "requestbattle"
 post '/games/multi/challengeResponse' => 'games#challengeResponse', as: "challengeResponse"
 get '/games/multi/:username' => 'games#multi', as: "games_multi"
 get '/games/pusher' => 'games#pusher'

 end

app/models/stat.rb
class Stat < ActiveRecord::Base
  attr_accessible :times_played, :total_score, :user_id
  belongs_to :user

  # validates :text, :rating, presence: true
  # validates :rating, numericality: true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  attr_accessible :username, :password, :password_confirmation, :is_admin
  has_one :stat

  validates :password, confirmation: true
  validates :password, presence: true, on: :create
  validates :username, presence: true
  validates :username, uniqueness: true

  def encrypt_password
    if password.present?
      # This generates a random string that helps me encrypt the password
      self.password_salt = BCrypt::Engine.generate_salt

      # This encrypts the password, using the salt we just created
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  # I can call this with User.authenticate(l,p)
  def self.authenticate(username, password)
    # This will auth a user
    user = User.find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :current_user
  before_filter :update_last_seen

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def update_last_seen
    # if @current_user == true
      @current_user.last_seen = DateTime.now
      @current_user.save
      # Below needs to be changed to 5 minutes or so in production
      @online_users = User.where("last_seen > ?",120.minutes.ago.to_s(:db))

  end

  def admin
    if @current_user.is_admin == true
      @admin = @current_user
    end
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path # halts request cycle
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def dashboard
  end

  def single
  end

  def multi
    @channelname = params[:username]
  end

  # def pusher
  #   Pusher[params[:username]].trigger('my_event', {
  #     message: 'hello world'
  #   })
  # end

  def gamebroadcast
    opponentChannelName       = params[:opponentChannelName]
    mySittingRubymonsPosition = params[:mySittingRubymonsPosition].values
    myFallingRubymonsPosition = params[:myFallingRubymonsPosition].values
    myCurrentXposition        = params[:myCurrentXposition]
    myCurrentYposition        = params[:myCurrentYposition]
    myUpcomingRubymonPair     = params[:myUpcomingRubymonPair]

    respond_to do |format|
      # format.html
      json_response = Pusher[opponentChannelName].trigger('gamebroadcast', {
        mySittingRubymonsPosition: mySittingRubymonsPosition,
        myFallingRubymonsPosition: myFallingRubymonsPosition,
        myCurrentXposition: myCurrentXposition,
        myCurrentYposition: myCurrentYposition,
        myUpcomingRubymonPair: myUpcomingRubymonPair
      })
      format.json { render :json => json_response }
    end

    # opponentChannelName = params[:opponentChannelName]
    # mySittingRubymonsPosition = params[:mySittingRubymonsPosition].values
    # myFallingRubymonsPosition = params[:myFallingRubymonsPosition].values
    # myCurrentXposition        = params[:myCurrentXposition]
    # myCurrentYposition        = params[:myCurrentYposition]
    # myUpcomingRubymonPair     = params[:myUpcomingRubymonPair]
    # Pusher[opponentChannelName].trigger('gamebroadcast', {
    #   mySittingRubymonsPosition: mySittingRubymonsPosition,
    #   myFallingRubymonsPosition: myFallingRubymonsPosition,
    #   myCurrentXposition: myCurrentXposition,
    #   myCurrentYposition: myCurrentYposition,
    #   myUpcomingRubymonPair: myUpcomingRubymonPair
    #   })

  end


  def requestBattle
    opponentChannelName = params[:opponentChannelName]
    challengerChannelName = params[:challengerChannelName]

    respond_to do |format|
      json_response = Pusher[opponentChannelName].trigger('promptRequestPopup', {
        message: "#{@current_user.username} has requested a battle with you!",
        challengerChannelName: @current_user.username
      })
      format.json { render :json => json_response }
    end
  end

  def challengeResponse
    opponentChannelName = params[:opponentChannelName]
    responseToChallenge = params[:responseToChallenge]
    if responseToChallenge == "true"
      messageToChallenger = "'#{@current_user.username}' has accepted your challenge! \nClick 'Ok' to start the countdown."
    else
      messageToChallenger = "'#{@current_user.username}' has rejected your challenge. \nClick 'Ok' to go back to dashboard."
    end

    respond_to do |format|
      json_response = Pusher[opponentChannelName].trigger('challengeResponse', {
      message: messageToChallenger,
      responseToChallenge: responseToChallenge,
      opponentChannelName: @current_user.username
      })
      format.json { render :json => json_response }
    end
  end

  def triggerBattleGame
    myOwnChannelName = params[:myOwnChannelName]
    opponentChannelName = params[:opponentChannelName]

    respond_to do |format|
      json_response_one = Pusher[myOwnChannelName].trigger('startCountdownAndGo', {message: "Start game!"})
      json_response_two = Pusher[opponentChannelName].trigger('startCountdownAndGo', {message: "Start game!"})
      json_response_total = { :json_response_one => json_response_one, :json_response_two => json_response_two }
      format.json { render :json => json_response_total }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :update_last_seen, only: [:new, :create]

  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to games_dashboard_path, alert: "Login successful"
    else
      flash.now.alert = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, alert: "Logged out"
  end

  def recentsessions
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :update_last_seen, only: [:new, :create]

  def new
    @user = User.new
  end

  # This is a POST and doesn't need a view
  # Instead it redirects or renders
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to games_dashboard_path, notice: "Signed up!"
    else
      flash[:notice] = "User exists."
      redirect_to new_session_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :update_last_seen, only: [:index]

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_rubymonset.html.erb
<div id="rubymon-set">
  <img class="rubymon-img" id="blank">
  <%= image_tag 'ruby_icon_red.png', class: 'rubymon-img', id: 'red' %>
  <%= image_tag 'ruby_icon_blue.png', class: 'rubymon-img', id: 'blue' %>
  <%= image_tag 'ruby_icon_green.png', class: 'rubymon-img', id: 'green' %>
  <%= image_tag 'ruby_icon_purple.png', class: 'rubymon-img', id: 'purple' %>
  <%= image_tag 'ruby_icon_yellow.png', class: 'rubymon-img', id: 'yellow' %>
  <%= image_tag 'ruby_icon_sad.png', class: 'rubymon-img', id: 'sad' %>
</div>

app/views/games/dashboard.html.erb
<div class="row">
  <div class="left_selection large-6 centered columns">
    <h1 class="big-ass-text">Single Mode</h1>
    <a href="/games/single" class="button round large">Play Single</a>
  </div>
    <h1 class="big-ass-text">Battle Mode</h1>
    <%= link_to 'Play Battle', sessions_recentsessions_path, class:'button round large', remote: true %>
  <div class="dropdown_current_users"></div>
</div>
</div>

<script type="text/javascript">

  // Enable pusher logging - don't include this in production
  Pusher.log = function(message) {
    if (window.console && window.console.log) {
      window.console.log(message);
    }
  };

  //////////////////////////////////////////////////////////////////////////////
  // DEFINE USER'S CHANNELS
  //////////////////////////////////////////////////////////////////////////////
  // 'http://d09eb96f1aef0dea4b31:57d70f45d23770529a1e@api.pusherapp.com/apps/51516'
  // var pusher = new Pusher(<%= ENV['d55ecc1d9e47eb42ed12'] %>);

  var usernameWithNoSpaces;
  var myOwnChannel;
  var commonChannel;
  var opponentChannelName;
  var commonChannelName;

  // var pusherKeycode = "'" + <%= ENV['PUSHER_KEY'].to_s %> + "'";
  var pusher = new Pusher('d55ecc1d9e47eb42ed12');
  establishMyOwnChannel();
  establishOpponentChannel();

  myOwnChannel.bind('gamebroadcast', function(rawGameboardData) {
    var atOpponentGameboard = rubyRageBattleMode.returnCtxOpponentGameboard();
    var atOpponentPreview = rubyRageBattleMode.returnCtxOpponentPreview();
    var reassembledGameboard = rubyRageBattleMode.reassembleTwoDimArray(rawGameboardData.mySittingRubymonsPosition);
    var reassembledCurrentRubyBox = rubyRageBattleMode.reassembleTwoDimArray(rawGameboardData.myFallingRubymonsPosition);
    var reassembledUpcomingRubymonPair = _.map(rawGameboardData.myUpcomingRubymonPair,
      function(string) {
        return parseInt(string);
      }
    );
    var myCurrentXposition = parseInt(rawGameboardData.myCurrentXposition);
    var myCurrentYposition = parseInt(rawGameboardData.myCurrentYposition);
    rubyRageBattleMode.paintOverOpponents( atOpponentGameboard, atOpponentPreview);
    rubyRageBattleMode.renderOpponentsSittingRubymons( reassembledGameboard, atOpponentGameboard);
    rubyRageBattleMode.renderOpponentsFallingRubymons( reassembledCurrentRubyBox , atOpponentGameboard, myCurrentXposition, myCurrentYposition);
    rubyRageBattleMode.renderOpponentsNextRubymons( reassembledUpcomingRubymonPair, atOpponentPreview);
  });

  myOwnChannel.bind('promptRequestPopup', function(data) {
    var response = confirm(data.message);
    var battleGameUrl = '/games/multi/' + data.challengerChannelName;
    var redirectCommand = "window.location.href = '" + battleGameUrl + "';"
    if (response == true) {
      setTimeout(redirectCommand, 100);
      challengeResponse(true, data.challengerChannelName);
    } else {
      challengeResponse(false, data.challengerChannelName);
    }
  });

  myOwnChannel.bind('challengeResponse', function(data) {
    alert(data.message);
    if (data.responseToChallenge === "true") {
      triggerBattleGame(data.opponentChannelName);
    } else {
      window.location.replace('/games/dashboard');
    }
  });

  myOwnChannel.bind('rubyonrage_test', function(data) {
    alert(data.message);
  });


  // commonChannel.bind('startCountdownAndGo'), function(data) {
  //   startCountdownAndGo();
  // }

  myOwnChannel.bind('startCountdownAndGo', function(data) {
    startCountdownAndGo();
  });



  //////////////////////////////////////////////////////////////////////////////
  // BATTLE RELATED EVENTS & FUNCTIONS
  //////////////////////////////////////////////////////////////////////////////

  function startSendingRequest() {
    $.ajax({
      url: "/games/gamebroadcast",
      type: "post",
      dataType: "json",
      data: {"opponentChannelName": opponentChannelName,
             "mySittingRubymonsPosition": gameboardInplay,
             "myFallingRubymonsPosition": currentRubyBox,
             "myCurrentXposition": currentX,
             "myCurrentYposition": currentY,
             "myUpcomingRubymonPair": rubymonPairsPreset[runningRubymonIndex]}
    })
  }

  function requestBattle(targetPlayerUsername) {
    $.ajax({
      url: "/games/multi/requestBattle",
      type: "post",
      dataType: "json",
      data: {"opponentChannelName": targetPlayerUsername,
             "challengerChannelName": usernameWithNoSpaces}
    })
  }

  function challengeResponse(answer, challengerUsername) {
    $.ajax({
      url: "/games/multi/challengeResponse",
      type: "post",
      dataType: "json",
      data: {"opponentChannelName": challengerUsername,
             "responseToChallenge": answer}
    })
  }

  function establishOpponentChannel() {
    var rawOpponentChannelName = $('#channel-name').text();
    opponentChannelName = rawOpponentChannelName.replace(/^\s+|\s+$/g, "");
  }

  function establishMyOwnChannel() {
    var username = $('.menubar_user').text();
    usernameWithNoSpaces = username.replace(/^\s+|\s+$/g, "");
    myOwnChannel = pusher.subscribe(usernameWithNoSpaces);
  }


  // function establishCommonChannel() {
  //   establishOpponentChannel();
  //   if (opponentChannelName < usernameWithNoSpaces) {
  //     commonChannelName = opponentChannelName + "_" + usernameWithNoSpaces;
  //   } else {
  //     commonChannelName = usernameWithNoSpaces + "_" + opponentChannelName;
  //   }
  //   commonChannel = pusher.subscribe(commonChannelName);
  // }

  function triggerBattleGame(targetPlayerUsername) {
    $.ajax({
      url: "/games/multi/triggerBattleGame",
      type: "post",
      dataType: "json",
      // data: {"commonChannelName": commonChannelName}
      data: {"opponentChannelName": targetPlayerUsername,
             "myOwnChannelName": usernameWithNoSpaces}
    })
  }

  function startCountdownAndGo() {
    setInterval(startSendingRequest, 300);
    newGame();
    setInterval( renderAll, 30 );
  }

</script>

app/views/games/multi.html.erb
<%= render 'rubymonset' %>

<div id="channel-name">
  <%= @channelname %>
</div>

<a href="/games/dashboard" class="button round">Back to Dashboard</a>

<div class="multi">
  <canvas width='300' height='480' id="gameboard"></canvas> <!-- TODO: NEED TO MAKE IT RESPONSIVE -->
  <canvas width='50' height='100' id="preview"></canvas> <!-- TODO: NEED TO MAKE IT RESPONSIVE -->

  <canvas width='200'></canvas>
  <canvas width='50' height='100' id="opponent-preview"></canvas> <!-- TODO: NEED TO MAKE IT RESPONSIVE -->
  <canvas width='300' height='480' id="opponent-gameboard"></canvas> <!-- TODO: NEED TO MAKE IT RESPONSIVE -->
</div>

<%= javascript_include_tag "rubyrage" %>

<script type="text/javascript">

  // Enable pusher logging - don't include this in production
  Pusher.log = function(message) {
    if (window.console && window.console.log) {
      window.console.log(message);
    }
  };

  //////////////////////////////////////////////////////////////////////////////
  // DEFINE USER'S CHANNELS
  //////////////////////////////////////////////////////////////////////////////
  // 'http://d09eb96f1aef0dea4b31:57d70f45d23770529a1e@api.pusherapp.com/apps/51516'
  // var pusher = new Pusher(<%= ENV['d55ecc1d9e47eb42ed12'] %>);

  var usernameWithNoSpaces;
  var myOwnChannel;
  var commonChannel;
  var opponentChannelName;
  var commonChannelName;

  // var pusherKeycode = "'" + <%= ENV['PUSHER_KEY'].to_s %> + "'";
  var pusher = new Pusher('d55ecc1d9e47eb42ed12');
  establishMyOwnChannel();
  establishOpponentChannel();

  myOwnChannel.bind('gamebroadcast', function(rawGameboardData) {
    var atOpponentGameboard = rubyRageBattleMode.returnCtxOpponentGameboard();
    var atOpponentPreview = rubyRageBattleMode.returnCtxOpponentPreview();
    var reassembledGameboard = rubyRageBattleMode.reassembleTwoDimArray(rawGameboardData.mySittingRubymonsPosition);
    var reassembledCurrentRubyBox = rubyRageBattleMode.reassembleTwoDimArray(rawGameboardData.myFallingRubymonsPosition);
    var reassembledUpcomingRubymonPair = _.map(rawGameboardData.myUpcomingRubymonPair,
      function(string) {
        return parseInt(string);
      }
    );
    var myCurrentXposition = parseInt(rawGameboardData.myCurrentXposition);
    var myCurrentYposition = parseInt(rawGameboardData.myCurrentYposition);
    rubyRageBattleMode.paintOverOpponents( atOpponentGameboard, atOpponentPreview);
    rubyRageBattleMode.renderOpponentsSittingRubymons( reassembledGameboard, atOpponentGameboard);
    rubyRageBattleMode.renderOpponentsFallingRubymons( reassembledCurrentRubyBox , atOpponentGameboard, myCurrentXposition, myCurrentYposition);
    rubyRageBattleMode.renderOpponentsNextRubymons( reassembledUpcomingRubymonPair, atOpponentPreview);
  });

  myOwnChannel.bind('promptRequestPopup', function(data) {
    var response = confirm(data.message);
    var battleGameUrl = '/games/multi/' + data.challengerChannelName;
    var redirectCommand = "window.location.href = '" + battleGameUrl + "';"
    if (response == true) {
      setTimeout(redirectCommand, 100);
      challengeResponse(true, data.challengerChannelName);
    } else {
      challengeResponse(false, data.challengerChannelName);
    }
  });

  myOwnChannel.bind('challengeResponse', function(data) {
    alert(data.message);
    if (data.responseToChallenge === "true") {
      triggerBattleGame(data.opponentChannelName);
    } else {
      window.location.replace('/games/dashboard');
    }
  });

  myOwnChannel.bind('rubyonrage_test', function(data) {
    alert(data.message);
  });


  // commonChannel.bind('startCountdownAndGo'), function(data) {
  //   startCountdownAndGo();
  // }

  myOwnChannel.bind('startCountdownAndGo', function(data) {
    startCountdownAndGo();
  });



  //////////////////////////////////////////////////////////////////////////////
  // BATTLE RELATED EVENTS & FUNCTIONS
  //////////////////////////////////////////////////////////////////////////////

  function startSendingRequest() {
    $.ajax({
      url: "/games/gamebroadcast",
      type: "post",
      dataType: "json",
      data: {"opponentChannelName": opponentChannelName,
             "mySittingRubymonsPosition": gameboardInplay,
             "myFallingRubymonsPosition": currentRubyBox,
             "myCurrentXposition": currentX,
             "myCurrentYposition": currentY,
             "myUpcomingRubymonPair": rubymonPairsPreset[runningRubymonIndex]}
    })
  }

  function requestBattle(targetPlayerUsername) {
    $.ajax({
      url: "/games/multi/requestBattle",
      type: "post",
      dataType: "json",
      data: {"opponentChannelName": targetPlayerUsername,
             "challengerChannelName": usernameWithNoSpaces}
    })
  }

  function challengeResponse(answer, challengerUsername) {
    $.ajax({
      url: "/games/multi/challengeResponse",
      type: "post",
      dataType: "json",
      data: {"opponentChannelName": challengerUsername,
             "responseToChallenge": answer}
    })
  }

  function establishOpponentChannel() {
    var rawOpponentChannelName = $('#channel-name').text();
    opponentChannelName = rawOpponentChannelName.replace(/^\s+|\s+$/g, "");
  }

  function establishMyOwnChannel() {
    var username = $('.menubar_user').text();
    usernameWithNoSpaces = username.replace(/^\s+|\s+$/g, "");
    myOwnChannel = pusher.subscribe(usernameWithNoSpaces);
  }


  // function establishCommonChannel() {
  //   establishOpponentChannel();
  //   if (opponentChannelName < usernameWithNoSpaces) {
  //     commonChannelName = opponentChannelName + "_" + usernameWithNoSpaces;
  //   } else {
  //     commonChannelName = usernameWithNoSpaces + "_" + opponentChannelName;
  //   }
  //   commonChannel = pusher.subscribe(commonChannelName);
  // }

  function triggerBattleGame(targetPlayerUsername) {
    $.ajax({
      url: "/games/multi/triggerBattleGame",
      type: "post",
      dataType: "json",
      // data: {"commonChannelName": commonChannelName}
      data: {"opponentChannelName": targetPlayerUsername,
             "myOwnChannelName": usernameWithNoSpaces}
    })
  }

  function startCountdownAndGo() {
    setInterval(startSendingRequest, 300);
    newGame();
    setInterval( renderAll, 30 );
  }

</script>

app/views/games/single.html.erb
<%= render 'rubymonset' %>

<canvas width='300' height='480' id="gameboard"></canvas> <!-- TODO: NEED TO MAKE IT RESPONSIVE -->
<canvas width='50' height='100' id="preview"></canvas> <!-- TODO: NEED TO MAKE IT RESPONSIVE -->

<br>
<a href="/games/dashboard" class="button round">Back to Dashboard</a>
<div id="start-button" class="button round">Start game</div>

<%= javascript_include_tag "rubyrage" %>

app/views/layouts/_navbar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "RubyOnRage", root_path, :class => "navbar_font" %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">


    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider hide-for-small"></li>
      <li class="has-dropdown not-click">
        <a class="menubar_user">
          <% if @current_user %>
          <%= @current_user.username %>
          <% else %>
          <%= link_to "Create Account", new_user_path %>
          <% end %>
        </a>
        <ul class="dropdown">
        <% if @current_user %>
          <li class><%= link_to "Sign Out", log_out_path %></li>
        </ul>
        <% end %>
      </li>
    </section>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Ruby Rage</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.1/underscore-min.js"></script>
    <script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
  </head>

  <body class="paperbg">
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>

</html>

app/views/users/_signupform.html.erb
 <%= form_for @user do |f| %>

 <% if @user.errors.any? %>
 <div class="error_messages">
  <h2>Bad input!</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation%><br>

<%= f.submit -%>


<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="small-4 large-centered columns">
    <h1>Create New Account</h1>
    <fieldset>
     <%= render 'signupform' %>
    </fieldset>
  </div>
</div>

app/views/users/new.js.erb
$('.form_area').hide()
$('.signup_area').html("<%=j render 'signupform' %>").show();

app/views/welcome/index.html.erb
<div class="row">
  <div class="large-centered">
    <br>
    <br>
    <br>
    <%= image_tag("big_ruby.png") %>

    <h1 class="big-ass-text small-12">Ruby on Rage</h1>

    <%= link_to 'PRESS PLAY', new_session_path, id:'welcomePlay', class:'play button round large', remote: true %>
    <div class="form_area"></div>
    <div class="signup_area"></div>

  </div>

</div>